# Experiment name
name: A2W2_Cosine

# Name of output directory. Checkpoints and logs will be saved at `pwd`/output_dir
output_dir: out

# Device to be used
device:
  # Use CPU or GPU (choices: cpu, cuda)
  type: cuda
  # GPU device IDs to be used. Only valid when device.type is 'cuda'
  gpu: [0,1]

distributed:
  dist_url: tcp://127.0.0.1:1111
  dist_backend: nccl

seed: 0

# Dataset loader
dataloader:
  # Dataset to train/validate (choices: imagenet, cifar10)
  dataset: imagenet
  # Number of categories in the specified dataset (choices: 1000, 10)
  num_classes: 1000
  # Path to dataset directory
  path: /mnt/data/hupeng/Downloads/ImageNet
  # Size of mini-batch
  batch_size: 256
  # Number of data loading workers
  workers: 32
  # Portion of training dataset to set aside for validation (range: [0, 1))
  val_split: 0.

resume:
  # Path to a checkpoint to be loaded. Leave blank to skip
  path:
  # Resume model parameters only
  lean: false

#============================ Model ============================================

# Supported model architecture
# choices:
#   ImageNet:
#     resnet18, resnet34, resnet50, resnet101, resnet152
#   CIFAR10:
#     resnet20, resnet32, resnet44, resnet56, resnet110, resnet1202
arch: resnet18

# Use pre-trained model
pre_trained: true

#============================ Quantization =====================================

quan:
  act: # (default for all layers)
    # Quantizer type (choices: lsq)
    mode: lsq
    # Grad function type (choices: default, tan, tanh)
    grad_mode: default
    # Bit width of quantized activation
    bit: 2
    # Each output channel uses its own scaling factor
    per_channel: false
    # Whether to use symmetric quantization
    symmetric: false
    # Quantize all the numbers to non-negative
    all_positive: true
  weight: # (default for all layers)
    # Quantizer type (choices: lsq)
    mode: lsq
    # Grad function type (choices: default, tan, tanh)
    grad_mode: default
    # Bit width of quantized weight
    bit: 2
    # Each output channel uses its own scaling factor
    per_channel: true
    # Whether to use symmetric quantization
    symmetric: true
    # Whether to quantize all the numbers to non-negative
    all_positive: false
  pact:
    use_pact: false
    version: v2
    alpha: 10
    lambda_alpha: 0.0002
  # Specify quantized bit width for some layers, like this:
  excepts: [conv1, fc]

#============================ Training / Evaluation ============================

# Evaluate the model without training
# If this field is true, all the bellowing options will be ignored
eval: false

epochs: 90

optimizer:
  # Optimizer type (choices: sgd, adam)
  mode: sgd
  sgd_params:
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.0001
  adam_params:
    learning_rate: 0.1
    betas: [0.9, 0.999]
    weight_decay: 0.0001
    amsgrad: false
quan_optimizer:
  # Optimizer type (choices: sgd, adam)
  mode: adam
  sgd_params:
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  adam_params:
    learning_rate: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 0.0
    amsgrad: false
weight_cluster_loss:
  use_wc_loss: true
  # weight_cluster_loss type (choices: naive, soft, topk, balanced)
  mode: topk
  coefficient: 0.000001
  topk: 3
  percentile: 0.68

# Learning rate scheduler
lr_scheduler:
  # Update learning rate per batch or epoch
  update_per_batch: false

  # Uncomment one of bellowing options to activate a learning rate scheduling

  # Fixed learning rate
  # mode: fixed

  # Step decay
  # mode: step
  # step_size: 30
  # gamma: 0.1

  # Multi-step decay
  # mode: multi_step
  # milestones: [30, 60, 90]
  # gamma: 0.1

  # Exponential decay
  # mode: exp
  # gamma: 0.95

  # Cosine annealing
  mode: cos
  lr_min: 0.000001
  cycle: 90

  # Cosine annealing with warm restarts
  # mode: cos_warm_restarts
  # lr_min: 0
  # cycle: 5
  # cycle_scale: 2
  # amp_scale: 0.5
